"""AI agent guide — generates README.md for the data directory."""

from collections import Counter
from pathlib import Path

import frontmatter


def _count_entries(entries_dir: Path) -> dict:
    """Scan entries and return counts by type and date range."""
    counts = Counter()
    earliest = None
    latest = None

    if not entries_dir.exists():
        return {"counts": counts, "earliest": earliest, "latest": latest, "total": 0}

    for md_file in (p for p in entries_dir.rglob("*.md") if p.name != "README.md"):
        try:
            post = frontmatter.load(str(md_file))
            entry_type = post.metadata.get("type", "unknown")
            counts[entry_type] += 1
            created = post.metadata.get("created", "")
            if isinstance(created, str) and created:
                date_str = created[:10]
            else:
                date_str = str(created)[:10] if created else None
            if date_str:
                if earliest is None or date_str < earliest:
                    earliest = date_str
                if latest is None or date_str > latest:
                    latest = date_str
        except Exception:
            continue

    return {"counts": counts, "earliest": earliest, "latest": latest, "total": sum(counts.values())}


def _collect_tags(entries_dir: Path) -> list[str]:
    """Collect all unique tags across entries."""
    tags = set()
    if not entries_dir.exists():
        return []
    for md_file in (p for p in entries_dir.rglob("*.md") if p.name != "README.md"):
        try:
            post = frontmatter.load(str(md_file))
            for tag in post.metadata.get("tags", []):
                tags.add(str(tag))
        except Exception:
            continue
    return sorted(tags)


def generate_readme(data_dir: Path) -> str:
    """Generate the README.md content with live stats."""
    entries_dir = data_dir / "entries"
    stats = _count_entries(entries_dir)
    tags = _collect_tags(entries_dir)

    # Build type folder tree
    type_dirs = ""
    for type_name in ["task", "note", "journal", "calendar"]:
        count = stats["counts"].get(type_name, 0)
        type_dirs += f"│   ├── {type_name}/              {count} entries\n"
        type_dirs += f"│   │   └── YYYY-MM/\n"
        type_dirs += f"│   │       └── <ULID>.md\n"

    date_range = ""
    if stats["earliest"] and stats["latest"]:
        date_range = f"\n**Date range:** {stats['earliest']} to {stats['latest']}\n"

    tag_list = ""
    if tags:
        tag_list = "\n### All tags\n\n" + ", ".join(f"`@{t}`" for t in tags) + "\n"

    return f"""\
# Bullet Terminal — Data Directory

This file describes the data in this directory so any AI agent can understand
and work with it. Auto-generated by bt — do not edit manually.

## What is this?

This is a bt (Bullet Terminal) data folder: plain Markdown files, one file per
entry. Every entry is one of four bullet types: a task, note, journal
reflection, or calendar event. Organized by type, then by month.

**Total entries:** {stats['total']}
{date_range}
## Directory structure

```
bullet-terminal/
├── entries/
│   ├── README.md         ← you are here
{type_dirs}├── .trash/           deleted entries — ignore; restore with bt trash → bt <n> restore
└── .index/
    └── bt.db             SQLite index (metadata + FTS5)
```

## Entry format

Every `.md` file in `entries/` follows this structure:

```yaml
---
created: '2026-04-01T18:29:20.178347+03:00'   # ISO 8601 with timezone
id: 01KN4TKN9JPJBPP9RMYAH4GPH2               # ULID (time-sortable, 26 chars)
type: journal                                  # task | note | journal | calendar
status: active                                 # tasks only: active | done | dropped
important: true                                # optional, boolean
tags:                                          # optional, list of strings
- home-reno
- backend
due: '2026-04-10'                              # optional, tasks only, ISO date
date: '2026-04-05'                             # optional, any type — resurface date
time: '14:30'                                  # optional, HH:MM 24h (always 24h on disk)
repeat: daily                                  # optional: daily|weekly|monthly|yearly
priority: high                                 # optional, any extra key is kept as-is
_gcal_id: uid:2026-04-05                       # keys starting with _ are private:
                                               #   kept on disk and in --json, but
                                               #   never shown in bt's own views
---

The entry body goes here. Plain text or markdown.
```

## Entry types and their bullets

| Type     | Bullet    | Purpose                                    |
|----------|-----------|-------------------------------------------|
| task     | .         | Actions to take — has a status lifecycle   |
| note     | -         | Ideas, facts, reference material           |
| journal  | =         | Reflections, feelings, stream of thought   |
| calendar | o         | Events with optional date and time         |

## Task statuses

- `active` — open, needs attention
- `done` — completed
- `dropped` — consciously abandoned (not deleted — the decision is preserved)

There is no `migrated` status. Tasks stay active until done or dropped.

## Fields and what sets them

These keys are written by bt itself. Each one is listed with the actions that
set, change, or clear it.

- `created` — the moment the entry was captured. Set once, never changed.
- `completed_date` — the day a task was resolved. Set by `done` **and** by
  `drop`, so it does not by itself mean the task was finished: read `status`
  to tell the two apart. Recurring tasks never get one (see `completions`).
- `focus_date` — the day the task was picked for the Focus Log. Set by the
  daily plan (`bt dp`), by `bt <n> focus`, and by capturing a task with no
  scope flag (`bt t ...`). Unpicked tasks lose it at the next daily plan. It
  holds one date only: picking the task again overwrites it.
- `week_date` — the first day of the week the task was picked for (Sunday by
  default; the week start is configurable). It is not a deadline.
  Set by the weekly plan (`bt wp`), by `bt <n> weeklog`, by `bt <n> focus`,
  and by capture without `-b`.
- `due` — a deadline the user typed. Tasks only.
- `date` — the day the user scheduled the entry for: an event's date, or the
  day a task, note or journal should resurface.
- `completions` — on recurring tasks (`repeat:`), the days the task was marked
  done. Consecutive days are stored as a range: `2026-03-28..2026-03-30` means
  the 28th, 29th and 30th. A recurring task stays `active`; each `done` adds
  today to this list.

### What bt does not record

- **Plans after resolution.** `done` and `drop` clear `focus_date` and
  `week_date`, so a resolved task no longer shows whether it was ever planned.
- **Plan history.** Only the latest `focus_date` and `week_date` are kept.
- **Edit history.** A file shows its current state only; when a body or field
  changed is not stored.
- **Uncaptured life.** Entries exist only for what the user chose to capture.

## Tags

Tags are plain strings stored in the `tags` list. They are pure organizational
labels — use them to group entries (`@backend`, `@health`) and filter across
dimensions (`bt @backend -@done`).

Special tags with meaning:
- `@habit` — marks a recurring task as a habit (tracked via `bt streak`)
{tag_list}
## First sentence convention

The first sentence of an entry's body (up to the first period) serves as its
title in list views. When reading entries, treat the first sentence as the
summary. A `>` after the first sentence in views indicates more content follows.

Entries created via AI capture ("bt this") have an explicit title as the first
line, followed by a blank line, then the full body.

## IDs

Entry IDs are ULIDs — Universally Unique Lexicographically Sortable Identifiers.
They encode creation time and are 26 characters long. Sorting by ID is equivalent
to sorting by creation time.

## Reading entries

To read all entries, glob `entries/**/*.md` and parse the YAML frontmatter.
The Python `python-frontmatter` library handles this, or any YAML parser
can split on the `---` delimiters.

To read only one type: `entries/task/**/*.md`, `entries/journal/**/*.md`, etc.

To read a specific period: `entries/*/2026-04/*.md` for all April 2026 entries.

To read one type for one period: `entries/journal/2026-04/*.md`.

## Creating entries

To create a new entry:
1. Generate a ULID for the ID
2. Set `created` to the current ISO 8601 timestamp with timezone
3. Set `type` to one of: task, note, journal, calendar
4. If type is task, set `status` to `active`
5. Write the file to `entries/{{type}}/YYYY-MM/<ULID>.md` using the type and month from `created`
6. YAML frontmatter between `---` delimiters, body after

## Modifying entries

Edit the frontmatter or body in place. The file path never changes — it stays
in its original type and month folder regardless of status changes.

## Habits

Habits are recurring task entries tagged `@habit` with a `repeat` field.
They live in `entries/task/` like other tasks — no separate storage. The
`bt h` command shows today's habit status, and `bt streak` shows streaks.

## SQLite index

`.index/bt.db` is a derived index — it can be rebuilt from the `.md` files
at any time via `bt rebuild`. It contains:
- Metadata table for structured queries
- FTS5 full-text search index

The `.md` files are the source of truth, not the database.
"""


def write_guide(data_dir):
    """Write the README.md guide to the entries directory."""
    entries_dir = data_dir / "entries"
    entries_dir.mkdir(parents=True, exist_ok=True)
    path = entries_dir / "README.md"
    content = generate_readme(data_dir)
    path.write_text(content)

    legacy = data_dir / "README.md"
    if legacy.exists():
        legacy.unlink()

    return path
