"""AI agent guide — generates README.md for the data directory."""

GUIDE = """\
# Bullet Terminal — Data Directory

This file describes the data in this directory so any AI agent can understand
and work with it. It is auto-generated by bt and updated with each release.

## What is this?

This is a Bullet Journal system stored as plain Markdown files. One file per
entry. Entries are tasks, notes, journal reflections, or calendar events.
Everything lives in `entries/` — there are no separate stores.

## Directory structure

```
bullet-terminal/
├── README.md             ← you are here
├── entries/
│   ├── 2026-03/
│   │   ├── <ULID>.md
│   │   └── ...
│   └── 2026-04/
│       └── ...
└── .index/
    └── bute.db           SQLite index (FTS5 + vectors)
```

## Entry format

Every `.md` file in `entries/` follows this structure:

```yaml
---
created: '2026-04-01T18:29:20.178347+03:00'   # ISO 8601 with timezone
id: 01KN4TKN9JPJBPP9RMYAH4GPH2               # ULID (time-sortable, 26 chars)
type: journal                                  # task | note | journal | calendar
status: active                                 # tasks only: active | done | dropped
important: true                                # optional, boolean
tags:                                          # optional, list of strings
- home-reno
- backend
due: '2026-04-10'                              # optional, tasks only, ISO date
scheduled_date: '2026-04-05'                   # optional, any type — resurface date
scheduled_time: '14:30'                        # optional, HH:MM 24h format
repeat: daily                                  # optional, recurrence pattern
extra_meta:                                    # optional, arbitrary key:value pairs
  priority: high
---

The entry body goes here. Plain text or markdown.
```

## Entry types and their BuJo signifiers

| Type     | Signifier | Purpose                                    |
|----------|-----------|-------------------------------------------|
| task     | .         | Actions to take — has a status lifecycle   |
| note     | -         | Ideas, facts, reference material           |
| journal  | =         | Reflections, feelings, stream of thought   |
| calendar | o         | Events with optional date and time         |

## Task statuses

- `active` — open, needs attention
- `done` — completed
- `dropped` — consciously abandoned (not deleted — the decision is preserved)

There is no `migrated` status. Tasks stay active until done or dropped.

## Tags

Tags are plain strings stored in the `tags` list. They serve two roles:
- **Labels** — organizing entries (`@backend`, `@health`)
- **Goals** — notes tagged `@goal` become goals; other tags on that note connect tasks to the goal

Special tags with meaning:
- `@today` — selected for the Focus Log (today's curated view)
- `@thisweek` — selected for this week's task focus
- `@goal` — marks a note as a goal
- `@habit` — marks a recurring task as a habit (tracked via `bt h`)

## First sentence convention

The first sentence of an entry's body (up to the first period) serves as its
title in list views. When reading entries, treat the first sentence as the
summary. A `>` after the first sentence in views indicates more content follows.

Entries created via AI capture ("bt this") have an explicit title as the first
line, followed by a blank line, then the full body.

## IDs

Entry IDs are ULIDs — Universally Unique Lexicographically Sortable Identifiers.
They encode creation time and are 26 characters long. Sorting by ID is equivalent
to sorting by creation time.

## Reading entries

To read all entries, glob `entries/**/*.md` and parse the YAML frontmatter.
The Python `python-frontmatter` library handles this, or any YAML parser
can split on the `---` delimiters.

## Creating entries

To create a new entry:
1. Generate a ULID for the ID
2. Set `created` to the current ISO 8601 timestamp with timezone
3. Set `type` to one of: task, note, journal, calendar
4. If type is task, set `status` to `active`
5. Write the file to `entries/YYYY-MM/<ULID>.md` using the month from `created`
6. YAML frontmatter between `---` delimiters, body after

## Modifying entries

Edit the frontmatter or body in place. The file path never changes — it stays
in its original month folder regardless of status changes.

## Habits

Habits are recurring task entries tagged `@habit` with a `repeat` field.
They live in `entries/` like everything else — no separate storage. The
`bt h` command shows today's habit status, and `bt streak` shows streaks.

## SQLite index

`.index/bute.db` is a derived index — it can be rebuilt from the `.md` files
at any time via `bt rebuild`. It contains:
- Metadata table for structured queries
- FTS5 full-text search index
- Vector embeddings for semantic search

The `.md` files are the source of truth, not the database.
"""


def write_guide(data_dir):
    """Write the README.md guide to the data directory."""
    path = data_dir / "README.md"
    path.write_text(GUIDE)
    return path
