"""AI agent guide — generates README.md for the data directory."""

from collections import Counter
from pathlib import Path

import frontmatter


def _count_entries(entries_dir: Path) -> dict:
    """Scan entries and return counts by type and date range."""
    counts = Counter()
    earliest = None
    latest = None

    if not entries_dir.exists():
        return {"counts": counts, "earliest": earliest, "latest": latest, "total": 0}

    for md_file in (p for p in entries_dir.rglob("*.md") if p.name != "README.md"):
        try:
            post = frontmatter.load(str(md_file))
            entry_type = post.metadata.get("type", "unknown")
            counts[entry_type] += 1
            created = post.metadata.get("created", "")
            if isinstance(created, str) and created:
                date_str = created[:10]
            else:
                date_str = str(created)[:10] if created else None
            if date_str:
                if earliest is None or date_str < earliest:
                    earliest = date_str
                if latest is None or date_str > latest:
                    latest = date_str
        except Exception:
            continue

    return {"counts": counts, "earliest": earliest, "latest": latest, "total": sum(counts.values())}


def _collect_tags(entries_dir: Path) -> list[str]:
    """Collect all unique tags across entries."""
    tags = set()
    if not entries_dir.exists():
        return []
    for md_file in (p for p in entries_dir.rglob("*.md") if p.name != "README.md"):
        try:
            post = frontmatter.load(str(md_file))
            for tag in post.metadata.get("tags", []):
                tags.add(str(tag))
        except Exception:
            continue
    return sorted(tags)


def generate_readme(data_dir: Path) -> str:
    """Generate the README.md content with live stats."""
    entries_dir = data_dir / "entries"
    stats = _count_entries(entries_dir)
    tags = _collect_tags(entries_dir)

    # Build type folder tree
    type_dirs = ""
    for type_name in ["task", "note", "journal", "calendar"]:
        count = stats["counts"].get(type_name, 0)
        type_dirs += f"│   ├── {type_name}/              {count} entries\n"
        type_dirs += f"│   │   └── YYYY-MM/\n"
        type_dirs += f"│   │       └── <ULID>.md\n"

    date_range = ""
    if stats["earliest"] and stats["latest"]:
        date_range = f"\n**Date range:** {stats['earliest']} to {stats['latest']}\n"

    tag_list = ""
    if tags:
        tag_list = "\n### All tags\n\n" + ", ".join(f"`@{t}`" for t in tags) + "\n"

    return f"""\
# Bullet Terminal — Data Directory

This file describes the data in this directory so any AI agent can understand
and work with it. Auto-generated by bt — do not edit manually.

## What is this?

This is a Bullet Journal system stored as plain Markdown files. One file per
entry. Entries are tasks, notes, journal reflections, or calendar events.
Organized by type, then by month.

**Total entries:** {stats['total']}
{date_range}
## Directory structure

```
bullet-terminal/
├── entries/
│   ├── README.md         ← you are here
{type_dirs}├── .trash/           deleted entries — ignore; restore with bt trash → bt <n> restore
└── .index/
    └── bt.db             SQLite index (FTS5 + vectors)
```

## Entry format

Every `.md` file in `entries/` follows this structure:

```yaml
---
created: '2026-04-01T18:29:20.178347+03:00'   # ISO 8601 with timezone
id: 01KN4TKN9JPJBPP9RMYAH4GPH2               # ULID (time-sortable, 26 chars)
type: journal                                  # task | note | journal | calendar
status: active                                 # tasks only: active | done | dropped
important: true                                # optional, boolean
tags:                                          # optional, list of strings
- home-reno
- backend
due: '2026-04-10'                              # optional, tasks only, ISO date
date: '2026-04-05'                             # optional, any type — resurface date
time: '14:30'                                  # optional, HH:MM 24h format
repeat: daily                                  # optional, recurrence pattern
extra_meta:                                    # optional, arbitrary key:value pairs
  priority: high
---

The entry body goes here. Plain text or markdown.
```

## Entry types and their BuJo signifiers

| Type     | Signifier | Purpose                                    |
|----------|-----------|-------------------------------------------|
| task     | .         | Actions to take — has a status lifecycle   |
| note     | -         | Ideas, facts, reference material           |
| journal  | =         | Reflections, feelings, stream of thought   |
| calendar | o         | Events with optional date and time         |

## Task statuses

- `active` — open, needs attention
- `done` — completed
- `dropped` — consciously abandoned (not deleted — the decision is preserved)

There is no `migrated` status. Tasks stay active until done or dropped.

## Tags

Tags are plain strings stored in the `tags` list. They are pure organizational
labels — use them to group entries (`@backend`, `@health`) and filter across
dimensions (`bt @backend -@done`).

Special tags with meaning:
- `@habit` — marks a recurring task as a habit (tracked via `bt streak`)
{tag_list}
## First sentence convention

The first sentence of an entry's body (up to the first period) serves as its
title in list views. When reading entries, treat the first sentence as the
summary. A `>` after the first sentence in views indicates more content follows.

Entries created via AI capture ("bt this") have an explicit title as the first
line, followed by a blank line, then the full body.

## IDs

Entry IDs are ULIDs — Universally Unique Lexicographically Sortable Identifiers.
They encode creation time and are 26 characters long. Sorting by ID is equivalent
to sorting by creation time.

## Reading entries

To read all entries, glob `entries/**/*.md` and parse the YAML frontmatter.
The Python `python-frontmatter` library handles this, or any YAML parser
can split on the `---` delimiters.

To read only one type: `entries/task/**/*.md`, `entries/journal/**/*.md`, etc.

To read a specific period: `entries/*/2026-04/*.md` for all April 2026 entries.

To read one type for one period: `entries/journal/2026-04/*.md`.

## Creating entries

To create a new entry:
1. Generate a ULID for the ID
2. Set `created` to the current ISO 8601 timestamp with timezone
3. Set `type` to one of: task, note, journal, calendar
4. If type is task, set `status` to `active`
5. Write the file to `entries/{{type}}/YYYY-MM/<ULID>.md` using the type and month from `created`
6. YAML frontmatter between `---` delimiters, body after

## Modifying entries

Edit the frontmatter or body in place. The file path never changes — it stays
in its original type and month folder regardless of status changes.

## Habits

Habits are recurring task entries tagged `@habit` with a `repeat` field.
They live in `entries/task/` like other tasks — no separate storage. The
`bt h` command shows today's habit status, and `bt streak` shows streaks.

## SQLite index

`.index/bt.db` is a derived index — it can be rebuilt from the `.md` files
at any time via `bt rebuild`. It contains:
- Metadata table for structured queries
- FTS5 full-text search index
- Vector embeddings for semantic search

The `.md` files are the source of truth, not the database.
"""


def write_guide(data_dir):
    """Write the README.md guide to the entries directory."""
    entries_dir = data_dir / "entries"
    entries_dir.mkdir(parents=True, exist_ok=True)
    path = entries_dir / "README.md"
    content = generate_readme(data_dir)
    path.write_text(content)

    legacy = data_dir / "README.md"
    if legacy.exists():
        legacy.unlink()

    return path
